#
# deposits
#

COMMON_METALS = [
    "ALUMINUM_ORE",
    "IRON_ORE",
    "COPPER_ORE",
]
MINERAL_DEPOSITS = ["SILICON_CRYSTALS", "QUARTZ_SAND"]
PRECIOUS_METAL_DEPOSITS = ["SILVER_ORE", "GOLD_ORE", "PLATINUM_ORE"]
RARE_METAL_DEPOSITS = ["MERITIUM_ORE", "URANITE_ORE"]
ICE_CRYSTAL_DEPOSITS = [
    "ICE_WATER",
    "AMMONIA_ICE",
    "LIQUID_HYDROGEN",
    "LIQUID_NITROGEN",
]
EXTRACTABLES = [
    "QUARTZ_SAND",
    "SILICON_CRYSTALS",
    "PRECIOUS_STONES",
    "ICE_WATER",
    "AMMONIA_ICE",
    "IRON_ORE",
    "COPPER_ORE",
    "SILVER_ORE",
    "ALUMINUM_ORE",
    "GOLD_ORE",
    "PLATINUM_ORE",
    "DIAMONDS",
    "URANITE_ORE",
    "MERITIUM_ORE",
]
#
# mounts
#
SURVEYOR_SYMBOLS = ["MOUNT_SURVEYOR_I", "MOUNT_SURVEYOR_II", "MOUNT_SURVEYOR_III"]
MINING_SYMBOLS = [
    "MOUNT_MINING_LASER_I",
    "MOUNT_MINING_LASER_II",
    "MOUNT_MINING_LASER_III",
]
#
# errors
#
SIPHON_SYMBOLS = ["MOUNT_GAS_SIPHON_I", "MOUNT_GAS_SIPHON_II", "MOUNT_GAS_SIPHON_III"]
ERRROR_COOLDOWN = 4000

ORBITAL_TYPES = ["ORBITAL_STATION", "MOON"]
PARENT_TYPES = ["PLANET", "GAS_GIANT"]
