
name: PyTest

  
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    
    runs-on: ubuntu-latest
    environment: 
      name: test environment
      url: none
    env:
      ST_DB_HOST: ${{ secrets.ST_HOST}}
      ST_DB_NAME: ${{ secrets.ST_NAME}}
      ST_DB_PASSWORD: ${{ secrets.ST_PASS}}
      ST_DB_PORT: ${{ secrets.ST_PORT}}
      ST_DB_USER: ${{ secrets.ST_USER}}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Test with pytest
        run: pytest -vv
